spring.application.name=space-debris-collision
spring.datasource.url=jdbc:postgresql://localhost:5432/debris-collision
spring.datasource.username=postgres
spring.datasource.password=Ritesh@0610
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}


spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# Use Redis as cache provider
spring.cache.type=redis

logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG
